// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREENKEYBOARD_H
#define UI_SCREENKEYBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenKeyBoard
extern void ui_ScreenKeyBoard_screen_init(void);
extern void ui_ScreenKeyBoard_screen_destroy(void);
extern lv_obj_t * ui_ScreenKeyBoard;
extern lv_obj_t * ui_ButtonScreenKeyBoardDo;
extern lv_obj_t * ui_ButtonScreenKeyBoardRe;
extern lv_obj_t * ui_ButtonScreenKeyBoardMi;
extern lv_obj_t * ui_ButtonScreenKeyBoardFa;
extern lv_obj_t * ui_ButtonScreenKeyBoardSo;
extern lv_obj_t * ui_ButtonScreenKeyBoardLa;
extern lv_obj_t * ui_ButtonScreenKeyBoardTi;
extern lv_obj_t * ui_ImageScreenKeyBoard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

