// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREENMUSIC_H
#define UI_SCREENMUSIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMusic
extern void ui_ScreenMusic_screen_init(void);
extern void ui_ScreenMusic_screen_destroy(void);
extern lv_obj_t * ui_ScreenMusic;
extern lv_obj_t * ui_ImageScreenMusic;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

