// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenMusic = NULL;
lv_obj_t * ui_ImageScreenMusic = NULL;
// event funtions

// build funtions

void ui_ScreenMusic_screen_init(void)
{
    ui_ScreenMusic = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageScreenMusic = lv_image_create(ui_ScreenMusic);
    lv_obj_set_width(ui_ImageScreenMusic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenMusic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenMusic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenMusic, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageScreenMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ScreenMusic_screen_destroy(void)
{
    if(ui_ScreenMusic) lv_obj_del(ui_ScreenMusic);

    // NULL screen variables
    ui_ScreenMusic = NULL;
    ui_ImageScreenMusic = NULL;

}
