// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREENLIGHT_H
#define UI_SCREENLIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenLight
extern void ui_ScreenLight_screen_init(void);
extern void ui_ScreenLight_screen_destroy(void);
extern lv_obj_t * ui_ScreenLight;
extern lv_obj_t * ui_ImageColorTemScreenLight;
extern lv_obj_t * ui_ArcColorTemScreenLight;
extern lv_obj_t * ui_LabelColorTemScreenLight;
extern lv_obj_t * ui_LabeColorTemRatioScreenLight;
extern lv_obj_t * ui_LabelColorTemDecScreenLight;
extern lv_obj_t * ui_LabelColorTemAddScreenLight;
extern lv_obj_t * ui_LabelColorTemCheckScreenLight;
extern lv_obj_t * ui_LabelColorTemOnOffScreenLight;
extern lv_obj_t * ui_LabelColorTemModeScreenLight;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

