// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenKeyBoard = NULL;
lv_obj_t * ui_ButtonScreenKeyBoardDo = NULL;
lv_obj_t * ui_LabelButtonScreenKeyBoardDo = NULL;
lv_obj_t * ui_ButtonScreenKeyBoardRe = NULL;
lv_obj_t * ui_LabelButtonScreenKeyBoardRe = NULL;
lv_obj_t * ui_ButtonScreenKeyBoardMi = NULL;
lv_obj_t * ui_LabelButtonScreenKeyBoardMi = NULL;
lv_obj_t * ui_ButtonScreenKeyBoardFa = NULL;
lv_obj_t * ui_LabelButtonScreenKeyBoardFa = NULL;
lv_obj_t * ui_ButtonScreenKeyBoardSo = NULL;
lv_obj_t * ui_LabelButtonScreenKeyBoardSo = NULL;
lv_obj_t * ui_ButtonScreenKeyBoardLa = NULL;
lv_obj_t * ui_LabelButtonScreenKeyBoardLa = NULL;
lv_obj_t * ui_ButtonScreenKeyBoardTi = NULL;
lv_obj_t * ui_LabelButtonScreenKeyBoardTi = NULL;
lv_obj_t * ui_ImageScreenKeyBoard = NULL;
// event funtions

// build funtions

void ui_ScreenKeyBoard_screen_init(void)
{
    ui_ScreenKeyBoard = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenKeyBoard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenKeyBoard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenKeyBoard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonScreenKeyBoardDo = lv_button_create(ui_ScreenKeyBoard);
    lv_obj_set_width(ui_ButtonScreenKeyBoardDo, 40);
    lv_obj_set_height(ui_ButtonScreenKeyBoardDo, 40);
    lv_obj_set_x(ui_ButtonScreenKeyBoardDo, -70);
    lv_obj_set_y(ui_ButtonScreenKeyBoardDo, -60);
    lv_obj_set_align(ui_ButtonScreenKeyBoardDo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScreenKeyBoardDo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonScreenKeyBoardDo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonScreenKeyBoardDo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonScreenKeyBoardDo, lv_color_hex(0xFF3B30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonScreenKeyBoardDo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonScreenKeyBoardDo, lv_color_hex(0xB22222), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_ButtonScreenKeyBoardDo, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_ButtonScreenKeyBoardDo, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_ButtonScreenKeyBoardDo, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelButtonScreenKeyBoardDo = lv_label_create(ui_ButtonScreenKeyBoardDo);
    lv_obj_set_width(ui_LabelButtonScreenKeyBoardDo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenKeyBoardDo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenKeyBoardDo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenKeyBoardDo, "Do");

    ui_ButtonScreenKeyBoardRe = lv_button_create(ui_ScreenKeyBoard);
    lv_obj_set_width(ui_ButtonScreenKeyBoardRe, 40);
    lv_obj_set_height(ui_ButtonScreenKeyBoardRe, 40);
    lv_obj_set_x(ui_ButtonScreenKeyBoardRe, -70);
    lv_obj_set_y(ui_ButtonScreenKeyBoardRe, 0);
    lv_obj_set_align(ui_ButtonScreenKeyBoardRe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScreenKeyBoardRe, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonScreenKeyBoardRe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonScreenKeyBoardRe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonScreenKeyBoardRe, lv_color_hex(0xFF9500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonScreenKeyBoardRe, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonScreenKeyBoardRe, lv_color_hex(0xCC6600), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_ButtonScreenKeyBoardRe, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_ButtonScreenKeyBoardRe, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_ButtonScreenKeyBoardRe, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelButtonScreenKeyBoardRe = lv_label_create(ui_ButtonScreenKeyBoardRe);
    lv_obj_set_width(ui_LabelButtonScreenKeyBoardRe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenKeyBoardRe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenKeyBoardRe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenKeyBoardRe, "Re");

    ui_ButtonScreenKeyBoardMi = lv_button_create(ui_ScreenKeyBoard);
    lv_obj_set_width(ui_ButtonScreenKeyBoardMi, 40);
    lv_obj_set_height(ui_ButtonScreenKeyBoardMi, 40);
    lv_obj_set_x(ui_ButtonScreenKeyBoardMi, -70);
    lv_obj_set_y(ui_ButtonScreenKeyBoardMi, 60);
    lv_obj_set_align(ui_ButtonScreenKeyBoardMi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScreenKeyBoardMi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonScreenKeyBoardMi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonScreenKeyBoardMi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonScreenKeyBoardMi, lv_color_hex(0xFFCC00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonScreenKeyBoardMi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonScreenKeyBoardMi, lv_color_hex(0xB8860B), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_ButtonScreenKeyBoardMi, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_ButtonScreenKeyBoardMi, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_ButtonScreenKeyBoardMi, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelButtonScreenKeyBoardMi = lv_label_create(ui_ButtonScreenKeyBoardMi);
    lv_obj_set_width(ui_LabelButtonScreenKeyBoardMi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenKeyBoardMi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenKeyBoardMi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenKeyBoardMi, "Mi");

    ui_ButtonScreenKeyBoardFa = lv_button_create(ui_ScreenKeyBoard);
    lv_obj_set_width(ui_ButtonScreenKeyBoardFa, 40);
    lv_obj_set_height(ui_ButtonScreenKeyBoardFa, 40);
    lv_obj_set_x(ui_ButtonScreenKeyBoardFa, 70);
    lv_obj_set_y(ui_ButtonScreenKeyBoardFa, -60);
    lv_obj_set_align(ui_ButtonScreenKeyBoardFa, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScreenKeyBoardFa, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonScreenKeyBoardFa, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonScreenKeyBoardFa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonScreenKeyBoardFa, lv_color_hex(0x34C759), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonScreenKeyBoardFa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonScreenKeyBoardFa, lv_color_hex(0x228B22), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_ButtonScreenKeyBoardFa, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_ButtonScreenKeyBoardFa, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_ButtonScreenKeyBoardFa, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelButtonScreenKeyBoardFa = lv_label_create(ui_ButtonScreenKeyBoardFa);
    lv_obj_set_width(ui_LabelButtonScreenKeyBoardFa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenKeyBoardFa, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenKeyBoardFa, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenKeyBoardFa, "Fa");

    ui_ButtonScreenKeyBoardSo = lv_button_create(ui_ScreenKeyBoard);
    lv_obj_set_width(ui_ButtonScreenKeyBoardSo, 40);
    lv_obj_set_height(ui_ButtonScreenKeyBoardSo, 40);
    lv_obj_set_x(ui_ButtonScreenKeyBoardSo, 70);
    lv_obj_set_y(ui_ButtonScreenKeyBoardSo, 0);
    lv_obj_set_align(ui_ButtonScreenKeyBoardSo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScreenKeyBoardSo, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonScreenKeyBoardSo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonScreenKeyBoardSo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonScreenKeyBoardSo, lv_color_hex(0x5AC8FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonScreenKeyBoardSo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonScreenKeyBoardSo, lv_color_hex(0x008B8B), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_ButtonScreenKeyBoardSo, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_ButtonScreenKeyBoardSo, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_ButtonScreenKeyBoardSo, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelButtonScreenKeyBoardSo = lv_label_create(ui_ButtonScreenKeyBoardSo);
    lv_obj_set_width(ui_LabelButtonScreenKeyBoardSo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenKeyBoardSo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenKeyBoardSo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenKeyBoardSo, "So");

    ui_ButtonScreenKeyBoardLa = lv_button_create(ui_ScreenKeyBoard);
    lv_obj_set_width(ui_ButtonScreenKeyBoardLa, 40);
    lv_obj_set_height(ui_ButtonScreenKeyBoardLa, 40);
    lv_obj_set_x(ui_ButtonScreenKeyBoardLa, 70);
    lv_obj_set_y(ui_ButtonScreenKeyBoardLa, 60);
    lv_obj_set_align(ui_ButtonScreenKeyBoardLa, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScreenKeyBoardLa, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonScreenKeyBoardLa, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonScreenKeyBoardLa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonScreenKeyBoardLa, lv_color_hex(0x007AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonScreenKeyBoardLa, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonScreenKeyBoardLa, lv_color_hex(0x00008B), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_ButtonScreenKeyBoardLa, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_ButtonScreenKeyBoardLa, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_ButtonScreenKeyBoardLa, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelButtonScreenKeyBoardLa = lv_label_create(ui_ButtonScreenKeyBoardLa);
    lv_obj_set_width(ui_LabelButtonScreenKeyBoardLa, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenKeyBoardLa, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenKeyBoardLa, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenKeyBoardLa, "La");

    ui_ButtonScreenKeyBoardTi = lv_button_create(ui_ScreenKeyBoard);
    lv_obj_set_width(ui_ButtonScreenKeyBoardTi, 40);
    lv_obj_set_height(ui_ButtonScreenKeyBoardTi, 40);
    lv_obj_set_x(ui_ButtonScreenKeyBoardTi, 0);
    lv_obj_set_y(ui_ButtonScreenKeyBoardTi, -90);
    lv_obj_set_align(ui_ButtonScreenKeyBoardTi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonScreenKeyBoardTi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonScreenKeyBoardTi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonScreenKeyBoardTi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonScreenKeyBoardTi, lv_color_hex(0x5856D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonScreenKeyBoardTi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ButtonScreenKeyBoardTi, lv_color_hex(0x4B0082), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_opa(ui_ButtonScreenKeyBoardTi, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(ui_ButtonScreenKeyBoardTi, 5, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_spread(ui_ButtonScreenKeyBoardTi, 5, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelButtonScreenKeyBoardTi = lv_label_create(ui_ButtonScreenKeyBoardTi);
    lv_obj_set_width(ui_LabelButtonScreenKeyBoardTi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelButtonScreenKeyBoardTi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelButtonScreenKeyBoardTi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelButtonScreenKeyBoardTi, "Ti");

    ui_ImageScreenKeyBoard = lv_image_create(ui_ScreenKeyBoard);
    lv_image_set_src(ui_ImageScreenKeyBoard, &ui_img_music_icon_png);
    lv_obj_set_width(ui_ImageScreenKeyBoard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenKeyBoard, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenKeyBoard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenKeyBoard, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageScreenKeyBoard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ScreenKeyBoard_screen_destroy(void)
{
    if(ui_ScreenKeyBoard) lv_obj_del(ui_ScreenKeyBoard);

    // NULL screen variables
    ui_ScreenKeyBoard = NULL;
    ui_ButtonScreenKeyBoardDo = NULL;
    ui_LabelButtonScreenKeyBoardDo = NULL;
    ui_ButtonScreenKeyBoardRe = NULL;
    ui_LabelButtonScreenKeyBoardRe = NULL;
    ui_ButtonScreenKeyBoardMi = NULL;
    ui_LabelButtonScreenKeyBoardMi = NULL;
    ui_ButtonScreenKeyBoardFa = NULL;
    ui_LabelButtonScreenKeyBoardFa = NULL;
    ui_ButtonScreenKeyBoardSo = NULL;
    ui_LabelButtonScreenKeyBoardSo = NULL;
    ui_ButtonScreenKeyBoardLa = NULL;
    ui_LabelButtonScreenKeyBoardLa = NULL;
    ui_ButtonScreenKeyBoardTi = NULL;
    ui_LabelButtonScreenKeyBoardTi = NULL;
    ui_ImageScreenKeyBoard = NULL;

}
