// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenLight = NULL;
lv_obj_t * ui_ImageColorTemScreenLight = NULL;
lv_obj_t * ui_ArcColorTemScreenLight = NULL;
lv_obj_t * ui_LabelColorTemScreenLight = NULL;
lv_obj_t * ui_LabeColorTemRatioScreenLight = NULL;
lv_obj_t * ui_LabelColorTemDecScreenLight = NULL;
lv_obj_t * ui_LabelColorTemAddScreenLight = NULL;
lv_obj_t * ui_LabelColorTemCheckScreenLight = NULL;
lv_obj_t * ui_LabelColorTemOnOffScreenLight = NULL;
lv_obj_t * ui_LabelColorTemModeScreenLight = NULL;
// event funtions

// build funtions

void ui_ScreenLight_screen_init(void)
{
    ui_ScreenLight = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageColorTemScreenLight = lv_image_create(ui_ScreenLight);
    lv_image_set_src(ui_ImageColorTemScreenLight, &ui_img_back_png);
    lv_obj_set_width(ui_ImageColorTemScreenLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageColorTemScreenLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageColorTemScreenLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageColorTemScreenLight, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageColorTemScreenLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcColorTemScreenLight = lv_arc_create(ui_ImageColorTemScreenLight);
    lv_obj_set_width(ui_ArcColorTemScreenLight, 120);
    lv_obj_set_height(ui_ArcColorTemScreenLight, 120);
    lv_obj_set_align(ui_ArcColorTemScreenLight, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcColorTemScreenLight, 60);
    lv_obj_set_style_arc_width(ui_ArcColorTemScreenLight, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcColorTemScreenLight, lv_color_hex(0xFF9329), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcColorTemScreenLight, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcColorTemScreenLight, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcColorTemScreenLight, lv_color_hex(0xFF9329), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcColorTemScreenLight, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelColorTemScreenLight = lv_label_create(ui_ImageColorTemScreenLight);
    lv_obj_set_width(ui_LabelColorTemScreenLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColorTemScreenLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColorTemScreenLight, -1);
    lv_obj_set_y(ui_LabelColorTemScreenLight, 27);
    lv_obj_set_align(ui_LabelColorTemScreenLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelColorTemScreenLight, "CCT");
    lv_obj_set_style_text_color(ui_LabelColorTemScreenLight, lv_color_hex(0xFF9329), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColorTemScreenLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelColorTemScreenLight, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeColorTemRatioScreenLight = lv_label_create(ui_ImageColorTemScreenLight);
    lv_obj_set_width(ui_LabeColorTemRatioScreenLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeColorTemRatioScreenLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeColorTemRatioScreenLight, 0);
    lv_obj_set_y(ui_LabeColorTemRatioScreenLight, -16);
    lv_obj_set_align(ui_LabeColorTemRatioScreenLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeColorTemRatioScreenLight, "60");
    lv_obj_set_style_text_color(ui_LabeColorTemRatioScreenLight, lv_color_hex(0xFCA54F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeColorTemRatioScreenLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeColorTemRatioScreenLight, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelColorTemDecScreenLight = lv_label_create(ui_ImageColorTemScreenLight);
    lv_obj_set_width(ui_LabelColorTemDecScreenLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColorTemDecScreenLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColorTemDecScreenLight, -70);
    lv_obj_set_y(ui_LabelColorTemDecScreenLight, -60);
    lv_obj_set_align(ui_LabelColorTemDecScreenLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelColorTemDecScreenLight, "CCT-");
    lv_obj_set_style_text_color(ui_LabelColorTemDecScreenLight, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColorTemDecScreenLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelColorTemDecScreenLight, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelColorTemDecScreenLight, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_LabelColorTemDecScreenLight, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelColorTemAddScreenLight = lv_label_create(ui_ImageColorTemScreenLight);
    lv_obj_set_width(ui_LabelColorTemAddScreenLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColorTemAddScreenLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColorTemAddScreenLight, 70);
    lv_obj_set_y(ui_LabelColorTemAddScreenLight, -60);
    lv_obj_set_align(ui_LabelColorTemAddScreenLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelColorTemAddScreenLight, "CCT+");
    lv_obj_set_style_text_color(ui_LabelColorTemAddScreenLight, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColorTemAddScreenLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelColorTemAddScreenLight, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelColorTemAddScreenLight, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_LabelColorTemAddScreenLight, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelColorTemCheckScreenLight = lv_label_create(ui_ImageColorTemScreenLight);
    lv_obj_set_width(ui_LabelColorTemCheckScreenLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColorTemCheckScreenLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColorTemCheckScreenLight, -50);
    lv_obj_set_y(ui_LabelColorTemCheckScreenLight, 70);
    lv_obj_set_align(ui_LabelColorTemCheckScreenLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelColorTemCheckScreenLight, "CCT/DIM");
    lv_obj_set_style_text_color(ui_LabelColorTemCheckScreenLight, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColorTemCheckScreenLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelColorTemCheckScreenLight, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelColorTemCheckScreenLight, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_LabelColorTemCheckScreenLight, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelColorTemOnOffScreenLight = lv_label_create(ui_ImageColorTemScreenLight);
    lv_obj_set_width(ui_LabelColorTemOnOffScreenLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColorTemOnOffScreenLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColorTemOnOffScreenLight, 62);
    lv_obj_set_y(ui_LabelColorTemOnOffScreenLight, 68);
    lv_obj_set_align(ui_LabelColorTemOnOffScreenLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelColorTemOnOffScreenLight, "On/Off");
    lv_obj_set_style_text_color(ui_LabelColorTemOnOffScreenLight, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColorTemOnOffScreenLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelColorTemOnOffScreenLight, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelColorTemOnOffScreenLight, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_LabelColorTemOnOffScreenLight, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelColorTemModeScreenLight = lv_label_create(ui_ImageColorTemScreenLight);
    lv_obj_set_width(ui_LabelColorTemModeScreenLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColorTemModeScreenLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColorTemModeScreenLight, -2);
    lv_obj_set_y(ui_LabelColorTemModeScreenLight, -98);
    lv_obj_set_align(ui_LabelColorTemModeScreenLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelColorTemModeScreenLight, "Matter");
    lv_obj_set_style_text_color(ui_LabelColorTemModeScreenLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColorTemModeScreenLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelColorTemModeScreenLight, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenLight_screen_destroy(void)
{
    if(ui_ScreenLight) lv_obj_del(ui_ScreenLight);

    // NULL screen variables
    ui_ScreenLight = NULL;
    ui_ImageColorTemScreenLight = NULL;
    ui_ArcColorTemScreenLight = NULL;
    ui_LabelColorTemScreenLight = NULL;
    ui_LabeColorTemRatioScreenLight = NULL;
    ui_LabelColorTemDecScreenLight = NULL;
    ui_LabelColorTemAddScreenLight = NULL;
    ui_LabelColorTemCheckScreenLight = NULL;
    ui_LabelColorTemOnOffScreenLight = NULL;
    ui_LabelColorTemModeScreenLight = NULL;

}
