// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_ScreenAirCon = NULL;
lv_obj_t * ui_ImageScreenAirCon = NULL;
lv_obj_t * ui_ArcScreenAirCon = NULL;
lv_obj_t * ui_LabelModeScreenAirCon = NULL;
lv_obj_t * ui_LabeModeRatioScreenAirCon = NULL;
lv_obj_t * ui_LabelModeDecScreenAirCon = NULL;
lv_obj_t * ui_LabelModeAddScreenAirCon = NULL;
lv_obj_t * ui_LabelModeCheckScreenAirCon = NULL;
lv_obj_t * ui_LabelModeOnOffScreenAirCon = NULL;
lv_obj_t * ui_LabelColorTemBrandScreenAirCon = NULL;
// event funtions

// build funtions

void ui_ScreenAirCon_screen_init(void)
{
    ui_ScreenAirCon = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenAirCon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenAirCon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAirCon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageScreenAirCon = lv_image_create(ui_ScreenAirCon);
    lv_image_set_src(ui_ImageScreenAirCon, &ui_img_cloud_back_png);
    lv_obj_set_width(ui_ImageScreenAirCon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenAirCon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenAirCon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageScreenAirCon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageScreenAirCon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ArcScreenAirCon = lv_arc_create(ui_ImageScreenAirCon);
    lv_obj_set_width(ui_ArcScreenAirCon, 120);
    lv_obj_set_height(ui_ArcScreenAirCon, 120);
    lv_obj_set_align(ui_ArcScreenAirCon, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_ArcScreenAirCon, 60);
    lv_obj_set_style_arc_width(ui_ArcScreenAirCon, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcScreenAirCon, lv_color_hex(0x00BFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcScreenAirCon, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcScreenAirCon, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcScreenAirCon, lv_color_hex(0x00BFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcScreenAirCon, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelModeScreenAirCon = lv_label_create(ui_ImageScreenAirCon);
    lv_obj_set_width(ui_LabelModeScreenAirCon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModeScreenAirCon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModeScreenAirCon, -1);
    lv_obj_set_y(ui_LabelModeScreenAirCon, 27);
    lv_obj_set_align(ui_LabelModeScreenAirCon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModeScreenAirCon, "COOL");
    lv_obj_set_style_text_color(ui_LabelModeScreenAirCon, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelModeScreenAirCon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelModeScreenAirCon, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeModeRatioScreenAirCon = lv_label_create(ui_ImageScreenAirCon);
    lv_obj_set_width(ui_LabeModeRatioScreenAirCon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeModeRatioScreenAirCon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeModeRatioScreenAirCon, 0);
    lv_obj_set_y(ui_LabeModeRatioScreenAirCon, -16);
    lv_obj_set_align(ui_LabeModeRatioScreenAirCon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeModeRatioScreenAirCon, "26℃");
    lv_obj_set_style_text_color(ui_LabeModeRatioScreenAirCon, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeModeRatioScreenAirCon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeModeRatioScreenAirCon, &ui_font_FontQingniao30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelModeDecScreenAirCon = lv_label_create(ui_ImageScreenAirCon);
    lv_obj_set_width(ui_LabelModeDecScreenAirCon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModeDecScreenAirCon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModeDecScreenAirCon, -70);
    lv_obj_set_y(ui_LabelModeDecScreenAirCon, -60);
    lv_obj_set_align(ui_LabelModeDecScreenAirCon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModeDecScreenAirCon, "Temp-");
    lv_obj_set_style_text_color(ui_LabelModeDecScreenAirCon, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelModeDecScreenAirCon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelModeDecScreenAirCon, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelModeDecScreenAirCon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_LabelModeDecScreenAirCon, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelModeAddScreenAirCon = lv_label_create(ui_ImageScreenAirCon);
    lv_obj_set_width(ui_LabelModeAddScreenAirCon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModeAddScreenAirCon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModeAddScreenAirCon, 70);
    lv_obj_set_y(ui_LabelModeAddScreenAirCon, -60);
    lv_obj_set_align(ui_LabelModeAddScreenAirCon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModeAddScreenAirCon, "Temp+");
    lv_obj_set_style_text_color(ui_LabelModeAddScreenAirCon, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelModeAddScreenAirCon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelModeAddScreenAirCon, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelModeAddScreenAirCon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_LabelModeAddScreenAirCon, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelModeCheckScreenAirCon = lv_label_create(ui_ImageScreenAirCon);
    lv_obj_set_width(ui_LabelModeCheckScreenAirCon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModeCheckScreenAirCon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModeCheckScreenAirCon, -46);
    lv_obj_set_y(ui_LabelModeCheckScreenAirCon, 70);
    lv_obj_set_align(ui_LabelModeCheckScreenAirCon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModeCheckScreenAirCon, "COOL/HEAT");
    lv_obj_set_style_text_color(ui_LabelModeCheckScreenAirCon, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelModeCheckScreenAirCon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelModeCheckScreenAirCon, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelModeCheckScreenAirCon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_LabelModeCheckScreenAirCon, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelModeOnOffScreenAirCon = lv_label_create(ui_ImageScreenAirCon);
    lv_obj_set_width(ui_LabelModeOnOffScreenAirCon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModeOnOffScreenAirCon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModeOnOffScreenAirCon, 65);
    lv_obj_set_y(ui_LabelModeOnOffScreenAirCon, 69);
    lv_obj_set_align(ui_LabelModeOnOffScreenAirCon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelModeOnOffScreenAirCon, "On/Off");
    lv_obj_set_style_text_color(ui_LabelModeOnOffScreenAirCon, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelModeOnOffScreenAirCon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelModeOnOffScreenAirCon, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelModeOnOffScreenAirCon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(ui_LabelModeOnOffScreenAirCon, 255, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_LabelColorTemBrandScreenAirCon = lv_label_create(ui_ImageScreenAirCon);
    lv_obj_set_width(ui_LabelColorTemBrandScreenAirCon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColorTemBrandScreenAirCon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColorTemBrandScreenAirCon, -2);
    lv_obj_set_y(ui_LabelColorTemBrandScreenAirCon, -98);
    lv_obj_set_align(ui_LabelColorTemBrandScreenAirCon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelColorTemBrandScreenAirCon, "Midea");
    lv_obj_set_style_text_color(ui_LabelColorTemBrandScreenAirCon, lv_color_hex(0x1E90FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColorTemBrandScreenAirCon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelColorTemBrandScreenAirCon, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenAirCon_screen_destroy(void)
{
    if(ui_ScreenAirCon) lv_obj_del(ui_ScreenAirCon);

    // NULL screen variables
    ui_ScreenAirCon = NULL;
    ui_ImageScreenAirCon = NULL;
    ui_ArcScreenAirCon = NULL;
    ui_LabelModeScreenAirCon = NULL;
    ui_LabeModeRatioScreenAirCon = NULL;
    ui_LabelModeDecScreenAirCon = NULL;
    ui_LabelModeAddScreenAirCon = NULL;
    ui_LabelModeCheckScreenAirCon = NULL;
    ui_LabelModeOnOffScreenAirCon = NULL;
    ui_LabelColorTemBrandScreenAirCon = NULL;

}
