// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREENAIRCON_H
#define UI_SCREENAIRCON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAirCon
extern void ui_ScreenAirCon_screen_init(void);
extern void ui_ScreenAirCon_screen_destroy(void);
extern lv_obj_t * ui_ScreenAirCon;
extern lv_obj_t * ui_ImageScreenAirCon;
extern lv_obj_t * ui_ArcScreenAirCon;
extern lv_obj_t * ui_LabelModeScreenAirCon;
extern lv_obj_t * ui_LabeModeRatioScreenAirCon;
extern lv_obj_t * ui_LabelModeDecScreenAirCon;
extern lv_obj_t * ui_LabelModeAddScreenAirCon;
extern lv_obj_t * ui_LabelModeCheckScreenAirCon;
extern lv_obj_t * ui_LabelModeOnOffScreenAirCon;
extern lv_obj_t * ui_LabelColorTemBrandScreenAirCon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

