// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_ScreenLight.h"
#include "screens/ui_ScreenAirCon.h"
#include "screens/ui_ScreenMusic.h"
#include "screens/ui_ScreenKeyBoard.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_cloud_back_png);    // assets/cloud_back.png
LV_IMG_DECLARE(ui_img_music_icon_png);    // assets/music_icon.png
LV_IMG_DECLARE(fire);
LV_IMG_DECLARE(rain);
LV_IMG_DECLARE(sea);

// FONTS
LV_FONT_DECLARE(ui_font_FontKaiTi22);
LV_FONT_DECLARE(ui_font_FontKaiTi30);
LV_FONT_DECLARE(ui_font_FontQingniao30);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
